### ISSUE TITLE
App failing due to missing SUBJECTS_DIR

### ISSUE THREAD

**Issue by soichih** [davhunt/app-benson14-retinotopy#1]
This App is failing with the following error message.

```
++ jq -r .freesurfer config.json
+ output=../5d8eacee13501c82d2d931c0/5967bffa9b45c212bbec8958/output
+ '[' -z 'hayashis@iu.edu 29511 *CPmh9xvKQKHE FSg0ijTusqaQc' ']'
+ echo hayashis@iu.edu 29511 '*CPmh9xvKQKHE' FSg0ijTusqaQc
+ cp -R ../5d8eacee13501c82d2d931c0/5967bffa9b45c212bbec8958/output ''
cp: cannot create directory '': No such file or directory
```

Brainlife doesn't set SUBJECTS_DIR, so it can not be used in `main`.

**Comment by soichih** [comment]
I've updated the main to the following.

```
#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=120gb,walltime=24:00:00
#PBS -N pRF
#PBS -V

set -e
set -x

freesurfer_dir=$(jq -r .freesurfer config.json)
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

subjects_dir=$(dirname $freesurfer_dir)

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://davhunt/neuropythy:1.4 python -m neuropythy benson14_retinotopy -d $subjects_dir output
```

I was able to work around the SUBJECTS_DIR, but now I am seeing this error message.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/scratch/hayashis/git/app-benson14-retinotopy/neuropythy/__main__.py", line 19, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/mnt/scratch/hayashis/git/app-benson14-retinotopy/neuropythy/__main__.py", line 16, in main
    return commands[argv[0]](argv[1:])
  File "neuropythy/commands/benson14_retinotopy.py", line 191, in main
    dtype=dtyp)
  File "neuropythy/mri/core.py", line 530, in cortex_to_image
    shape = self.image_dimensions if shape is None else shape
  File "/usr/local/lib/python2.7/dist-packages/pimms/immutable.py", line 135, in _imm_getattribute
    value = memfn(*[getattr(self, arg) for arg in args])
  File "neuropythy/mri/core.py", line 248, in image_dimensions
    img = images[key]
  File "/usr/local/lib/python2.7/dist-packages/pimms/util.py", line 596, in __getitem__
    return self._examine_val(k, ps.PMap.__getitem__(self, k))
  File "/usr/local/lib/python2.7/dist-packages/pimms/util.py", line 592, in _examine_val
    val = val()
  File "neuropythy/freesurfer/core.py", line 350, in <lambda>
    ims['lh_white_mask'] = lambda:_make_imm_mask(mgh_images['ribbon'].get_data(), 2)
  File "/usr/local/lib/python2.7/dist-packages/pimms/util.py", line 596, in __getitem__
    return self._examine_val(k, ps.PMap.__getitem__(self, k))
  File "/usr/local/lib/python2.7/dist-packages/pyrsistent/_pmap.py", line 71, in __getitem__
    return PMap._getitem(self._buckets, key)
  File "/usr/local/lib/python2.7/dist-packages/pyrsistent/_pmap.py", line 68, in _getitem
    raise KeyError(key)
KeyError: 'ribbon'

```
