### ISSUE TITLE
Local neuropythy directory gets injected into the App

### ISSUE THREAD

**Issue by soichih** [davhunt/app-benson14-retinotopy#4]
Brad and I are seeing this error message.

```
@hayashis there's a bug with the prf:
Traceback (most recent call last):
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
   exec code in run_globals
 File "/N/dc2/scratch/brlife/karst-workflows/5d936cd94ff6d325e8376404/5dae5a171aa34c61793cf8e5/neuropythy/__main__.py", line 8, in <module>
   from neuropythy.commands import (commands)
 File "neuropythy/commands/__init__.py", line 10, in <module>
   from . import surface_to_image    as _s2i
ImportError: cannot import name surface_to_image
```

When this App runs, it should be using the neuropythy installed on the Docker container, but the local (on workdir) ./neuropythy module is used instead. As ./neuropythy is not necessary, it should be removed to avoid this error message.

Actually, this repo contains a lot of unnecessary files / directories that is inflating the app size (and .git). I recommend starting over with just the following files.

```
main
config.json.sample
Dockerfile
build.sh
.gitignore
```

**Comment by davhunt** [comment]
Hm yeah I think I just worked around using the python module for some reason I'll see if I can fix it before tomorrow
